### ISSUE TITLE
frida analysis issue

### ISSUE THREAD

**Issue by silver-liq9118** [no-1-of-gamza/Gamza_MobSF#1]
https://github.com/no-1-of-gamza/Gamza_MobSF/blob/f932fb2904ad66314fab1c0fd506c6fb5ba7bdb9/app.py#L315

@yura-Choi  Please Check This Funtion and Please Fix them...

API Code is 
https://github.com/no-1-of-gamza/Gamza_MobSF/blob/f932fb2904ad66314fab1c0fd506c6fb5ba7bdb9/mobSF_rest_API.py#L190

**Comment by yura-Choi** [comment]
로직 이슈로, 앱 실행 이후 곧바로 분석을 종료시키는 함수가 실행되어 발생한 경우였습니다.
분석 종료 전 sleep 등의 구문을 이용하여 앱이 실행될 때까지 대기하도록 하면 실행된 앱의 모습을 볼 수 있었습니다.
